theme: jekyll-theme-dinky
title: About Xiaoxuan
description: Xiaoxuan is a software engineer and she currently works for Microsoft. She writes code every day because she enjoys it. She lives in Shanghai, China.
show_downloads: false
