theme: jekyll-theme-dinky
title: About this site
description: This is the personal site of Xiaoxuan Wang. Xiaoxuan is a software engineer and she currently works for Microsoft. Her favorite programming language is Ruby.
show_downloads: false
